import { DB } from 'themes/config';

export const DEPENDENCIES = [
  DB.USERS,
  DB.USER_ROLES,
  DB.CATEGORIES,
  DB.TAXONOMIES,
  DB.ACTIONS,
  DB.ACTORS,
  DB.ACTORTYPES,
  DB.ACTORTYPE_TAXONOMIES,
  DB.ACTOR_ACTIONS,
  DB.ACTOR_CATEGORIES,
  DB.ACTION_CATEGORIES,
];
